# !tyml @cargo/Cargo
[workspace]
resolver = "2"
members = [
    "src/men-sharp",
    "src/men-sharp-asm",
    "src/men-sharp-codegen",
    "src/men-sharp-compiler",
    "src/men-sharp-diagnostics",
    "src/men-sharp-dotnet",
    "src/men-sharp-parser",
    "src/men-sharp-semantics",
]

[workspace.dependencies]
men-sharp-parser = { path = "src/men-sharp-parser" }
men-sharp-semantics = { path = "src/men-sharp-semantics" }
men-sharp-compiler = { path = "src/men-sharp-compiler" }
men-sharp-dotnet = { path = "src/men-sharp-dotnet" }
men-sharp-asm = { path = "src/men-sharp-asm" }
men-sharp-codegen = { path = "src/men-sharp-codegen" }
men-sharp-diagnostics = { path = "src/men-sharp-diagnostics" }
sys-locale = "0.3.2"
regex = "1.11.1"
bumpalo = { version = "3.17.0", features = ["allocator-api2"] }
allocator-api2 = "0.2.21"
extension-fn = "1.2.0"
typeid = "1.0.3"
rayon = "1.10.0"
timescope = "0.1.3"
