# !tyml @cargo/Cargo
[package]
name = "men-sharp-codegen"
version = "0.1.1"
edition = "2024"

[dependencies]
men-sharp-diagnostics = { workspace = true }
timescope = { workspace = true }
men-sharp-asm = { workspace = true }
men-sharp-parser = { workspace = true }
men-sharp-semantics = { workspace = true }
rustc-hash = { workspace = true }
