[package]
name = "men-sharp"
version = "0.1.2"
edition = "2024"

[dependencies]
timescope = { workspace = true }
men-sharp-compiler = { workspace = true }
men-sharp-parser = { workspace = true }
men-sharp-semantics = { workspace = true }
men-sharp-codegen = { workspace = true }
men-sharp-diagnostics = { workspace = true }
sys-locale = { workspace = true }
mimalloc = { workspace = true }
