[package]
name = "men-sharp-parser"
version = "0.1.1"
edition = "2024"

[dependencies]
men-sharp-diagnostics = { workspace = true }
regex = { workspace = true }
bumpalo = { workspace = true }
allocator-api2 = { workspace = true }
extension-fn = { workspace = true }
typeid = { workspace = true }
rustc-hash = { workspace = true }
